name: surf_util
version: 1.0.3
description: A flutter library with list of helpful classes and utilities for everyday usage.
repository: "https://github.com/surfstudio/flutter-surf-util"
issue_tracker: "https://github.com/surfstudio/flutter-surf-util/issues"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
